export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const TOGGLE_SEARCH_IS_CLOSED = "TOGGLE_SEARCH_IS_CLOSED";
export const SET_SEARCH_IS_CLOSED = "SET_SEARCH_IS_CLOSED";
export const SET_IS_SEARCHING = "SET_IS_SEARCHING";
export const ADD_RESULTS = "ADD_RESULTS";
