export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const TOGGLE_SEARCH_IS_CLOSED = "TOGGLE_SEARCH_IS_CLOSED";
export const SET_SEARCH_IS_CLOSED = "SET_SEARCH_IS_CLOSED";
export const SET_IS_SEARCHING = "SET_IS_SEARCHING";

export const SET_RESULTS = "SET_RESULTS";
export const ADD_RESULTS = "ADD_RESULTS";
export const SET_LAST_UPDATE = "SET_LAST_UPDATE";
export const SET_IS_LOADING = "SET_IS_LOADING";

export const SET_FOOD = "SET_FOOD";
export const SET_QUANTITY = "SET_QUANTITY";
export const SET_PORTION_WEIGHT_IN_GRAMS = "SET_PORTION_WEIGHT_IN_GRAMS";

export const SET_DATE = "SET_DATE";
export const SET_CURRENT_ID = "SET_CURRENT_ID";
